### ISSUE TITLE
Timer for opening gate at Gothik

### ISSUE THREAD

**Issue by lkrocek** [DeadlyBossMods/DBM-WotLK#15]
We were on Gothik the Harvester 25m yesterday for fun, on realm Frostmourne2 of Warmane he had a 50 seconds shorter timer for gate open than is displayed.

So I can't confirm the same on 10m but short it about 50seconds on 25m at least.

**Comment by MysticalOS** [comment]
This is on retail? no 10 or 25 on classic era or tbc classic retail isn't the fight like 2 seconds long?

Either way though I probably won't look at this issue for a few weeks/months. Not until dust has settled from 9.2

**Comment by Nightw4re** [comment]
no it's not, close it please.
