### ISSUE TITLE
Unable to install DBM

### ISSUE THREAD

**Issue by LogansUA** [DeadlyBossMods/DBM-WotLK#17]
**Describe the bug**
I'm doing something wrong

I've downloaded latest release version and there's not Core and GUI folders therefore addon is not working for me saying that dependency missing `DBM-Core`.
If I'm using the DBM Core and GUI from older version `4.52r4442` it's not working either, getting Lua errors.
If I'm using the [DBM-Unified](https://github.com/DeadlyBossMods/DBM-Unified) this as addition to DMB-WotlLK
I'm gettin an error below

**Do you have an error log of what happened?**

<details>

```
Message: Interface\AddOns\DBM-Core\modules\Commands.lua:426: attempt to call method 'LoadGUI' (a nil value)
Time: Tue Jul 12 22:23:35 2022
Count: 2
Stack: Interface\AddOns\DBM-Core\modules\Commands.lua:426: in function `?'
Interface\FrameXML\ChatFrame.lua:4049: in function <Interface\FrameXML\ChatFrame.lua:3997>
[C]: in function `ChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:3660: in function `ChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:3698: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>
```

</details>

**To Reproduce**

Just install `DBM-WotLK` addon

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes, same thing

**Which version of DeadlyBossMods are you using?**

[r307](https://github.com/DeadlyBossMods/DBM-WotLK/releases/tag/r307)

**Was it working in a previous version? If yes, which was the last good one?**

I've previously had 4.52r4442 guess it's the version from 2013 year

I'm clearly doing something wrong.
Maybe it make sense to add some small tutorial for installing it?

**Comment by MysticalOS** [comment]
DBM-WoTLK is for retail, not private servers, we provide no support for private server setup. you'll have to find very obsolete modules that work with that very obsolete version of game. You won't find those files here

**Comment by LogansUA** [comment]
That was kinda rude, but anyway thanks for the answer
