### ISSUE TITLE
Can't receive DBM_SetStage event in Mimiron encounter

### ISSUE THREAD

**Issue by realyigo** [DeadlyBossMods/DBM-WotLK#35]
**Describe the bug**
DBM is awsome, it helps me a lot.
I write an addon, which is heavily rely on stage information from DBM.
But in Mimiron encounter, I can't receive DBM_SetStage event. Can you help fix it?
The game version is wotlk 3.4.1

**Do you have an error log of what happened?**

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by MysticalOS** [comment]
Receive how? callback? it should work minus phase detection is a bit iffy on mimiron on non english locals

**Comment by realyigo** [comment]
> Receive how? callback? it should work minus phase detection is a bit iffy on mimiron on non english locals

Yes,   callback.   I register DBM_SetStage event, but can't receive event in mimiron encounter. 
I read the mimiron code,  there are SetStage(0) for retail version, but not for classic version. I think that's why I can't receive DBM_SetStage event. 
Another thing I am confused is that there are no SetStage() for classic version. But self:GetStage(2), self:GetStage(3) worked in function mod:OnSync(event, args).

**Comment by MysticalOS** [comment]
There is only a single version of mod. the classic version pulls retail version of mod.

I'm looking right at code, seems fine. Setstage(0) is present and working. it just increments stage by 1 every time it's called.

get stage is obviously used for timers or event handlers

I'm more leaning to fact something is wrong with your callback code.

**Comment by realyigo** [comment]
There is a "not self:IsClassic()" for self:SetStage(0).  Classicic version can't receive DBM_SetStage event. SetStage fire DBM_SetStage event.
----------------------------------------------------------------------
function mod:UNIT_SPELLCAST_SUCCEEDED(uId, _, spellId)
--Modern phasing path, where boss unit Ids exist.
if spellId == 34098 and self:AntiSpam(5, 1) and **not self:IsClassic()** then--ClearAllDebuffs
	**self:SetStage(0)**

**Comment by MysticalOS** [comment]
Oh I see what you mean. then yeah that's been broken all of classic

**Comment by realyigo** [comment]
> There is only a single version of mod. the classic version pulls retail version of mod.
> 
> I'm looking right at code, seems fine. Setstage(0) is present and working. it just increments stage by 1 every time it's called.
> 
> get stage is obviously used for timers or event handlers
> 
> I'm more leaning to fact something is wrong with your callback code.

There is a "not self:IsClassic()" for self:SetStage(0).  Classicic version can't receive DBM_SetStage event. SetStage fire DBM_SetStage event.
function mod:UNIT_SPELLCAST_SUCCEEDED(uId, _, spellId)
--Modern phasing path, where boss unit Ids exist.
if spellId == 34098 and self:AntiSpam(5, 1) and **not self:IsClassic()** then--ClearAllDebuffs
	**self:SetStage(0)**
