### ISSUE TITLE
Sindragosa Bllister cold CD before Phase 3 would be much higher

### ISSUE THREAD

**Issue by diw1** [DeadlyBossMods/DBM-WotLK#46]
![BllisteringCold](https://github.com/DeadlyBossMods/DBM-WotLK/assets/13313686/81184257-f5b3-4666-b06e-eec19a1e2e42)
From the WCL log it looks like 95 seconds CD after last cast, and reset after 35%

**Comment by MysticalOS** [comment]
I kinda wish I could get the direct WCL link so i can run more detailed expression on it.

**Comment by MysticalOS** [comment]
the CD is 67 in stage 2, in stage 1 that timer isn't suppose to start there at all, that was a bug. the only timer that's supposed to start is the one off the air phase yells. but even then it's got up to a 30 second variation

fixing bug with the CD timer starting incorrectly on cast though if it's not stage 2. However the bug wouldn't have actually impacted timer accuracy during fight except for starting one useless timer before an air phase.

the timer that starts on air phase would have overrided it anhways and that timer is 80-110seconds variation, it starts an 80 second timer on air phase start,. then on phase 2 it resets to 35 seconds and THEN it starts an actual CD loop.

**Comment by diw1** [comment]
As our logs are private, there is another log I found. 

https://classic.warcraftlogs.com/reports/x9XFYfb4darNMyZ7#translate=true&fight=66&type=casts&hostility=1&source=205

Seems I could not find an exact timestamp on WCL to indicate either the start of air phase or the yell there. 

I understand this is a CD and not always use it when it off CD, So I just want to find the minimum interval.
