### ISSUE TITLE
Lord Marrowgar only using 7 markers for Impale instead of 8

### ISSUE THREAD

**Issue by davidgroves** [DeadlyBossMods/DBM-WotLK#49]
I find, and I think others will find, Lord Marrowgar easier to do if there is a stack mark on the main tank.

With DBM marking impales with all markers, it isn't possible to keep a marker on the main target.

It is possible to disable marking impales, but this isn't ideal as the markers for impales are very useful.

If 7 people have been impaled, you are likely wiping anyway.

**Comment by MysticalOS** [comment]
Merged and took it one step further by now have it reset to skull every new set of impales. no reason to start at last used icon for an entirely new set, it should consistently start at skull for every new set. in reality it likely will now only use (when fight done properly) 3 icons and nothing more
