### ISSUE TITLE
Trial of the Crusader issues

### ISSUE THREAD

**Issue by Molkree** [DeadlyBossMods/DBM-WotLK#53]
**Describe the bug**

For the earlier bosses RP timers are too long, bosses become attackable a couple of seconds earlier. For Faction Champions boss DBM didn't record boss kill even though I see `ENCOUNTER_END` event in the log.

**Do you have an error log of what happened?**

[TrialOfCrusaderTranscriptor.zip](https://github.com/DeadlyBossMods/DBM-WotLK/files/13289508/TrialOfCrusaderTranscriptor.zip)

**Screenshots**
![image](https://github.com/DeadlyBossMods/DBM-WotLK/assets/12860284/4e069711-2d56-4608-b84d-cc5626b265b1)

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No

**Which version of DeadlyBossMods are you using?**
Core DBM-10.1.31-51-gee86516
DBM-Raids-WoTLK-r320-14-gccb2838

**Was it working in a previous version? If yes, which was the last good one?**
Dunno

**Additional context**

**Comment by MysticalOS** [comment]
If iI recall encounter events are buggy so ignored. and win detection only works based on localization because the involved bosses is also random.
