### ISSUE TITLE
DBM Not Working in RS after update

### ISSUE THREAD

**Issue by Feronas** [DeadlyBossMods/DBM-WotLK#67]
**Describe the bug**

**Do you have an error log of what happened?**

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by MysticalOS** [comment]
Completion of mod unification:

With latest updates, DBM has completed long process of making every module a hybrid mod that auto loads to conditions and needs of current client running from. As such, no custom modules exist for specific game versions any more. Every DBM mod is designed to "just work" regardless of what addons folder it's thrown into.

You can basically copy any DBM addon from classic to retail, or other way around, any flavor and it auto loads/changes to code base needed for that game version.

This also reduces issues with mod managers going forward when multiple versions/copies of same module exist in diff packages, such as wrath classic package also containing same modules as wrath retail package. Distributing same files in two diff packages can cause problems. This also lead to user confusion more often than not. A user would search for DBM wrath and find the retail modules for it and not the classic ones.

Going forward, the retail ones are also the classic ones. The only caveat is that if you download just deadly boss mods core, you don't actually have raid modules for cataclysm, wrath, tbc, or vanilla until you also download the packages for those modules. I've decided this is still better with all the perks and confusion that it eliminates after a brief confusion for users who one minute had DBM Core+Custom wrath modules in a single package to DBM Core+Unified wrath modules as two separate downloads.

TL/DR. 
The modules that work on retail, also work on cata, wrath, tbc, or vanilla classic.
For retail Download DBM Core and DBM Dungeons and you're good to go. For cataclysm Download DBM Core + DBM Cataclysm + DBM Dungeons (optionally can also download wrath, tbc and vanilla modules for cataclysm too that's up to you). Wrath and vanilla is same thing. Core + Game version package + Dungeons (if you want em).
Easier more targeted updating.
